services:
  backend:
    container_name: my_backend
    image: python:3.10
    volumes:
      - ./backend:/backend
    working_dir: /backend
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=""  # Prevent TensorFlow from using the GPU
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python  # Use pure Python implementation for protocol buffers
    ports:
      - 8050:8050
    command: sh -c "pip install poetry && poetry install && poetry run python -m api.main"

  frontend:
    container_name: my_frontend
    image: node:alpine
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    environment:
      - IS_DOCKER=true
    command: sh -c "npm install && npm config set loglevel warn && npm start"
    ports:
      - 3020:3020
  
  messaging:
    container_name: rabbitmq_img_class
    image: rabbitmq:3-management
    ports:
      - 5772:5672
      - 15772:15672
    restart: always
    
