models:
  paths:
    model: models/heroes.h5
    indices: models/heroes_class_indices.json
data:
  input: data_input

train:
  params:
    batch_size: 32
    epochs: 10
    validation_split: 0.4

  resources:
    train_dataset: "train_dataset"
    ignore_folders:
      - "_quotes"
